# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  AWS_REGION: 'us-east-2'
  ECR_REGISTRY: '440744252508.dkr.ecr.us-east-2.amazonaws.com'
  ECR_REPOSITORY: 'willsmsvfargate'
  SERVICE_NAME: 'nestjs-service'
  CLUSTER_NAME: 'nestjs-cluster'
  TASK_FAMILY: 'TestFargate'

stages:
  - stage: Build
    displayName: 'Build and push'
    jobs:
      - job: Build
        displayName: 'Build and push'
        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'

        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'

        - task: Docker@2
          displayName: Docker Build
          inputs:
            repository: $(ECR_REPOSITORY)
            command: 'build'
            Dockerfile: '**/Dockerfilefg'
            buildContext: '$(Build.SourcesDirectory)'
            arguments: '--build-arg NPM_TOKEN=$(System.AccessToken)'
        - task: ECRPushImage@1
          inputs:
            awsCredentials: 'TESAWSDEV'
            regionName: $(AWS_REGION)
            imageSource: 'imagename'
            sourceImageName: $(ECR_REPOSITORY)
            sourceImageTag: '$(Build.BuildId)'
            repositoryName: $(ECR_REPOSITORY)
            pushTag: '$(Build.BuildId)'

  - stage: Deploy
    displayName: 'Deploy to Fargate'
    jobs:
      - job: Deploy
        displayName: 'Update Fargate Service'
        steps:
          - task: AWSShellScript@1
            inputs:
              awsCredentials: 'TESAWSDEV'
              regionName: 'us-east-2'
              scriptType: 'inline'
              inlineScript: |
                # You can write your script inline here
                TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $(TASK_FAMILY))

          - task: AWSCLI@1
            displayName: Update Service
            inputs:
              awsCredentials: 'TESAWSDEV'
              regionName: 'us-east-2'
              awsCommand: 'ecs'
              awsSubCommand: 'update-service'
              awsArguments: '--cluster $(CLUSTER_NAME) --service $(SERVICE_NAME) --task-definition $(TASK_FAMILY)'