# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest


variables:
  - name: AWS_REGION
    value: 'us-east-2'
  - name: ECR_REGISTRY
    value: '440744252508.dkr.ecr.us-east-2.amazonaws.com'
  - name: ECR_REPOSITORY
    value: 'willsmsvfargate'
  - name: SERVICE_NAME
    value: 'nestjs-service'
  - name: CLUSTER_NAME
    value: 'nestjs-cluster'
  - name: TASK_FAMILY
    value: 'willsmsvfargate'
  - group: Tesdev

stages:

  - stage: Deploy
    displayName: 'Deploy to Fargate'
    jobs:
      - job: Deploy
        displayName: 'Update Fargate Service'
        steps:
          - task: replacetokens@6
            inputs:
              sources: 'willsmsvfargate-task-definition.tkn.json'

          - task: AWSCLI@1
            inputs:
              awsCredentials: 'TESAWSDEV'
              regionName: $(AWSREGION)
              awsCommand: 'ecs'
              awsSubCommand: 'register-task-definition'
              awsArguments: '--cli-input-json file://willsmsvfargate-task-definition.json'
          
          - task: AWSCLI@1
            inputs:
              awsCredentials: 'TESAWSDEV'
              regionName: '$(AWSREGION)'
              awsCommand: 'ecs'
              awsSubCommand: 'update-service'
              awsArguments: '--cluster nestjs-cluster --service willsmsvfargate-svc --task-definition willsmsvfargate-task --desired-count 1 '         

