# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  displayName: Docker Build
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfilefg'
    arguments: '--build-arg NPM_TOKEN=$(System.AccessToken)'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'TESAWSDEV'
    regionName: 'us-east-2'
    imageSource: 'imagename'
    sourceImageName: 'testfargate'
    sourceImageTag: '$(Build.BuildId)'
    repositoryName: 'testfargate'
    pushTag: '$(Build.BuildId)'



